# Site settings
title: Giancarlo Salton
description: 'A Ph.D. student passionate about Machine Learning.'
url: 'http://giancds.github.io'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Giancarlo Salton'
  email: giancds.salton@mydit.ie
  twitter_username: giancds
  github_username:  giancds
  linkedin_username:  giancds

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
